name: CI

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different
  pull_request:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme  # Add any other dependencies here

    - name: Build documentation
      run: |
        cd docs  # Change to your documentation directory if different
        make html

    - name: Upload HTML to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: html-docs
        path: docs/_build/html/