# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  doc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Doxypypy
        run: pip install git+https://github.com/Dan-wanna-M/doxypypy@master --force-reinstall
      - name: Doxygen Deploy Action
        uses: Dan-Wanna-M/doxygen-github-pages-action@v0.1.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/dev/html
          config_file: Doxyfile
          target_folder: ${{ github.ref_name }}/
          pre_build: |
            chmod +x docs/header_gen.sh
            ./docs/header_gen.sh ${{ github.ref_name }}
            chmod +x py_filter.sh
            export VERSION=${{ github.ref_name }}
            echo "PROJECT_NUMBER = $VERSION" >> Doxyfile
      - name: Generate index.html
        run: |
          python docs/index_gen.py --version ${{ github.ref_name }}
      - name: Update index.html
        uses: JamesIves/github-pages-deploy-action@v4.6.4 # https://github.com/detekt/detekt/pull/7685
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/index/
          target_folder: index/
          clean: false


  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
